### PR TITLE
To avoid ibus-pinyin-setup crash in python3 env.

### PR DESCRIPTION
**Pull request by qiangzhao**
Update ibus-setup-pinyin.in: to avoid ibus-pinyin-setup crash in pure python3 env.

### CODE REVIEW

**Comment by qiangzhao** [comment]
@fujiwarat @epico Could you please review this request, for some down-stream users are complaining when updating to python3. I have confirmed this way can work fine. 
Thanks!

**Comment by fujiwarat** [comment]
CC'ing @phuang 

LGTM

**Comment by qiangzhao** [comment]
> CC'ing @phuang
> 
> LGTM

Thank you for the kind review.

**Comment by fujiwarat** [comment]
@qiangzhao BTW, almost IBus engines have migrated IBusConfig to GSettings; https://github.com/ibus/ibus/wiki/GSettingsMigration
I have a plan to drop IBusConfig in 1.6.

**Comment by qiangzhao** [comment]
> @qiangzhao BTW, almost IBus engines have migrated IBusConfig to GSettings; https://github.com/ibus/ibus/wiki/GSettingsMigration
> I have a plan to drop IBusConfig in 1.6.

Hi @fujiwarat : Thanks! what A nice plan! Does that mean this work still need more hands to contribute to?

**Comment by epico** [comment]
Yes, please help on ibus-pinyin project.

The example code is in ibus-libpinyin project.

**Comment by qiangzhao** [comment]
> Yes, please help on ibus-pinyin project.
> 
> The example code is in ibus-libpinyin project.

I got it. Thank you all!

**Pull request merged**
